
module.exports = {
    solicitudes: [

        {
            codigo: '0001',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0002',
            nombre: 'Garrett Winters',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0003',
            nombre: 'Ashton Cox',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0004',
            nombre: 'Cedric Kelly',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0005',
            nombre: 'Airi Satou',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0006',
            nombre: 'Brielle Williamson',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0007',
            nombre: 'Herrod Chandler',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0008',
            nombre: 'Rhona Davidson',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0009',
            nombre: 'Colleen Hurst',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0010',
            nombre: 'Sonya Frost',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0011',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0012',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0013',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0014',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0015',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0016',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0017',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0018',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0019',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0020',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0021',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0022',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0023',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0024',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0025',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0025',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0025',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0025',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0025',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0025',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0025',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0025',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0025',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0025',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0025',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0025',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0025',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0025',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0025',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0025',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0025',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0025',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0025',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0025',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0025',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0025',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0025',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        


    ],
};
