module.exports = {
    prediosd: [

        {
            codigo: '0001',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0002',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0003',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0004',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0005',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0006',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0007',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0008',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0009',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        {
            codigo: '0010',
            nombre: 'Tiger Nixon',
            documento: '12345789',
            area: '1000',
            areac: '500',
            direccion: 'Cll 4 # 6-7',
            barrio: 'Ciudad Jardin',
            estrato: '5',
        },
        


    ],
};
